image: node:latest

cache: 
  paths:
    - node_modules/

variables:
  repo_registry: 'registry.gitlab.com/fluxrankinggroup/fr-core'

stages:
  - install_dependencies
  - compile
  - testingbuild
  - testing


install_dependencies:
  stage: install_dependencies
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

