image: node:latest

cache: 
  paths:
    - node_modules/

stages:
  - install_dependencies
  - docker_build

install_dependencies:
  stage: install_dependencies
  script:
    - npm install
    - npm install gulp -g
    - gulp
  artifacts:
    paths:
      - node_modules/
      - dist/

# greift auf Dockerfile zu
dockerbuild:
  image: docker:latest
  services:
    - docker:dind
  stage: dockerbuild
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --pull -t registry.gitlab.com/tum.icm/icm-server:latest .
    - docker push registry.gitlab.com/tum.icm/icm-server:latest
  artifacts:
    paths:
      - node_modules/