image: node:latest

cache: 
  paths:
    - node_modules/

variables:
  repo_registry: 'registry.gitlab.com/fluxrankinggroup/fr-core'

stages:
  - install_dependencies
  - dockerbuild


install_dependencies:
  stage: install_dependencies
  script:
    - npm install
#    - npm install --only=dev
    - npm install gulp -g
    - gulp
  artifacts:
    paths:
      - node_modules/
      - dist/

# greift auf Dockerfile zu
dockerbuild:
  image: docker:latest
  services:
    - docker:dind
  stage: dockerbuild
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --pull -t $repo_registry/testing:latest .
    - docker push $repo_registry/testing:latest
  artifacts:
    paths:
      - node_modules/